// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCgAjjppkdVfzOVVeVunvmcmobZkimi1xE',
    appId: '1:257765008122:web:eff0d567e87ace8cd35f43',
    messagingSenderId: '257765008122',
    projectId: 'fruit-hub-19186',
    authDomain: 'fruit-hub-19186.firebaseapp.com',
    storageBucket: 'fruit-hub-19186.firebasestorage.app',
    measurementId: 'G-XPXHTPC8XE',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD-LcnOO1N9vNCeFZbKNH6BFPiVnpkWnA4',
    appId: '1:257765008122:android:cd7a00c8413fed22d35f43',
    messagingSenderId: '257765008122',
    projectId: 'fruit-hub-19186',
    storageBucket: 'fruit-hub-19186.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBQk33W1LdA4C0A2LWo1gwkzywku1xPV24',
    appId: '1:257765008122:ios:1e340cc7792eed57d35f43',
    messagingSenderId: '257765008122',
    projectId: 'fruit-hub-19186',
    storageBucket: 'fruit-hub-19186.firebasestorage.app',
    iosBundleId: 'com.example.fruitHub',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBQk33W1LdA4C0A2LWo1gwkzywku1xPV24',
    appId: '1:257765008122:ios:1e340cc7792eed57d35f43',
    messagingSenderId: '257765008122',
    projectId: 'fruit-hub-19186',
    storageBucket: 'fruit-hub-19186.firebasestorage.app',
    iosBundleId: 'com.example.fruitHub',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCgAjjppkdVfzOVVeVunvmcmobZkimi1xE',
    appId: '1:257765008122:web:6697d2f01be25c93d35f43',
    messagingSenderId: '257765008122',
    projectId: 'fruit-hub-19186',
    authDomain: 'fruit-hub-19186.firebaseapp.com',
    storageBucket: 'fruit-hub-19186.firebasestorage.app',
    measurementId: 'G-4QPPQXHD9K',
  );
}
